name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou outra versão que você esteja usando

      - name: Install dependencies
        run: npm install

      - name: Print reopsitory variables (debug)
        run: |
          echo "Secret key is ${{ secrets.SECRET_KEY }}"
          echo "Env is ${{ vars.ENVIRONMENT }}"

      - name: Run Cypress tests
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          npx cypress run --env ENVIRONMENT=$ENVIRONMENT,SECRET_KEY=$SECRET_KEY
