name: CI

env:
  ENVIRONMENT: ${{vars.ENVIRONMENT}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou outra versão que você esteja usando

      - name: Install dependencies
        run: npm install

      - name: Print environment variables (debug)
        run: |
          echo "Secret key is ${{secrets.SECRET_KEY}}"
          echo "Env is ${{vars.ENVIRONMENT}}"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "SECRET_KEY=$SECRET_KEY"

      - name: Run Cypress tests
        run: |
          npx cypress run --env ENVIRONMENT=$ENVIRONMENT,SECRET_KEY=$SECRET_KEY
