name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cypress run
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      uses: cypress-io/github-action@v5
